#!/bin/sh
if [ "$1" = "install" ]; then
    $(dirname $0)/dotfiles-install.py
elif [ "$1" = "update" ]; then
    $(dirname $0)/dotfiles-update.sh
else
    echo "Invalid parameters for dotfiles command: $@"
    echo "Available parameter(s):"
    echo "- install"
    echo "- upgrade"
    exit 1
fi
