---
# Font smoothing (see https://colinstodd.com/posts/tech/fix-macos-catalina-fonts-after-upgrade.html)
- shell: defaults -currentHost write -globalDomain AppleFontSmoothing -int 0

# Expand save panel by default (see https://www.defaults-write.com/expand-save-panel-default/)
- shell: defaults write -globalDomain NSNavPanelExpandedStateForSaveMode -bool TRUE
- shell: defaults write -globalDomain NSNavPanelExpandedStateForSaveMode2 -bool TRUE

# Disable smart quotes and smart dashed as they’re annoying when typing code
- shell: defaults write -globalDomain NSAutomaticQuoteSubstitutionEnabled -bool FALSE
- shell: defaults write -globalDomain NSAutomaticDashSubstitutionEnabled -bool FALSE

# Disable auto-correct
- shell: defaults write -globalDomain NSAutomaticSpellingCorrectionEnabled -bool FALSE

# Disable press-and-hold for keys in favor of key repeat
- shell: defaults write -globalDomain ApplePressAndHoldEnabled -bool FALSE

# Always show the crollbars
- shell: defaults write -globalDomain AppleShowScrollBars -string Always

# Enabling full keyboard access for all controls (e.g. enable Tab in modal dialogs)
- shell: defaults write -globalDomain AppleKeyboardUIMode -int 3

# Stop Photos from opening when a new SD card, etc. is being plugged in (see http://lifehacker.com/prevent-photos-on-os-x-from-opening-up-automatically-1754586297)
- shell: defaults write com.apple.ImageCapture disableHotPlug -bool TRUE

# Use AirDrop over every interface
- shell: defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool TRUE

# Disable the “Are you sure you want to open this application?” dialog
- shell: defaults write com.apple.LaunchServices LSQuarantine -bool FALSE

# Don't create .DS_Store files on network volumes
- shell: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool TRUE

# Disable the sound effects on boot
- shell: nvram SystemAudioVolume=" "
  become: true


# -----------------------------------------------------------------------------
# Finder
# -----------------------------------------------------------------------------

# Show the complete path in the Finder title bar
- shell: defaults write com.apple.finder _FXShowPosixPathInTitle -bool TRUE

# Show folders first
- shell: defaults write com.apple.finder _FXSortFoldersFirst -bool TRUE

# Disable the warning when changing a file extension
- shell: defaults write com.apple.finder FXEnableExtensionChangeWarning -bool FALSE

# Always open everything in list view (see https://www.defaults-write.com/change-default-view-style-in-os-x-finder/)
- shell: defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Disable the warning before emptying the Trash
- shell: defaults write com.apple.finder WarnOnEmptyTrash -bool FALSE


# -----------------------------------------------------------------------------
# Safari
# -----------------------------------------------------------------------------

- shell: defaults write com.apple.Safari ShowFavoritesBar -bool FALSE
- shell: defaults write com.apple.Safari IncludeInternalDebugMenu -bool TRUE
- shell: defaults write com.apple.Safari IncludeDevelopMenu -bool TRUE
- shell: defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool TRUE
- shell: defaults write com.apple.Safari "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" -bool TRUE
- shell: defaults write -globalDomain WebKitDeveloperExtras -bool TRUE


# -----------------------------------------------------------------------------
# Other applications
# -----------------------------------------------------------------------------

# Disable automatic spell checking
- shell: defaults write com.apple.mail SpellCheckingBehavior -string "NoSpellCheckingEnabled"
