tap 'homebrew/bundle'

brew 'antigen'
brew 'asciidoctor'
brew 'ansible'
brew 'awscli'
brew 'bat'
brew 'coreutils'
brew 'direnv'
brew 'dog'
brew 'fasd'
brew 'ffmpeg'
brew 'fluxctl'
brew 'git'
brew 'httpie' # https://httpie.org/
brew 'imagemagick'
brew 'jid' # https://github.com/fiatjaf/jiq
brew 'jq'
brew 'lazydocker' # https://github.com/jesseduffield/lazydocker
brew 'maven'
brew 'ocrmypdf'
brew 'pandoc'
brew 'pwgen'
brew 'pstree'
brew 'pup' # https://github.com/ericchiang/pup
brew 'rbenv'
brew 'rg' # https://blog.burntsushi.net/ripgrep/
brew 'rsync'
brew 'ruby'
brew 'telnet'
brew 'terraform'
brew 'tesseract-lang' # Allow German for OCRmyPDF
brew 'tldr' # https://tldr.sh/
brew 'trash'
brew 'tree'
brew 'wifi-password'
brew 'wget'
brew 'yank'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'

tap 'homebrew/cask'
cask 'ngrok'

# https://github.com/Homebrew/homebrew-cask-fonts
tap 'homebrew/cask-fonts'
cask 'font-arial'
cask 'font-courier-new'
cask 'font-jetbrainsmono-nerd-font'
cask 'font-firacode-nerd-font'

# https://github.com/colindean/homebrew-fonts-nonfree
tap 'colindean/fonts-nonfree'
cask 'font-microsoft-office'

# https://github.com/AdoptOpenJDK/homebrew-openjdk
tap 'AdoptOpenJDK/openjdk'
cask 'adoptopenjdk15'
