#!/bin/zsh

# Setup script for installing the basic macOS dependencies.
# The script is designed to be executed once but is macos to be idempotent, so that it can be
# executed multiple times and each subsequent execution only installs what is not already existent.

BASE_DIRECTORY="$(dirname ${0:a})"
for INCLUDE_FILE in ${BASE_DIRECTORY}/**/*.zsh(N); do
  source ${INCLUDE_FILE}
done
